export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_INSTALLATION = 'CHECK_INSTALLATION';
export const RETRIEVE_DOMAIN_REPOSITORIES = 'RETRIEVE_DOMAIN_REPOSITORIES';
export const EDIT_USER = 'EDIT_USER';