export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_COMMENT = 'GET_COMMENT';
export const RETRIEVE_COMMENTS = 'RETRIEVE_COMMENTS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT'
