export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const GET_DOCUMENT = 'GET_DOCUMENT';
<<<<<<< HEAD
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const RETRIEVE_DOCUMENTS = 'RETRIEVE_DOCUMENTS';
export const ATTACH_TAG = 'ATTACH_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const ATTACH_SNIPPET = 'ATTACH_SNIPPET';
export const REMOVE_SNIPPET = 'REMOVE_SNIPPET';
export const ATTACH_PARENT = 'ATTACH_PARENT';
export const REMOVE_PARENT = 'REMOVE_PARENT';
export const ATTACH_UPLOAD_FILE = 'ATTACH_UPLOAD_FILE';
export const REMOVE_UPLOAD_FILE = 'REMOVE_UPLOAD_FILE';
export const ADD_CAN_WRITE = 'ADD_CAN_WRITE';
export const REMOVE_CAN_WRITE = 'REMOVE_CAN_WRITE';
export const ADD_CAN_READ = 'ADD_CAN_READ';
export const REMOVE_CAN_READ = 'REMOVE_CAN_READ';
=======
export const RETRIEVE_DOCUMENTS = 'RETRIEVE_DOCUMENTS';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const ATTACH_DOCUMENT_TAG = 'ATTACH_DOCUMENT_TAG';
export const REMOVE_DOCUMENT_TAG = 'REMOVE_DOCUMENT_TAG';
export const ATTACH_DOCUMENT_SNIPPET = 'ATTACH_DOCUMENT_SNIPPET';
export const REMOVE_DOCUMENT_SNIPPET = 'REMOVE_DOCUMENT_SNIPPET';
export const ATTACH_DOCUMENT_PARENT = 'ATTACH_DOCUMENT_PARENT';
export const REMOVE_DOCUMENT_PARENT = 'REMOVE_DOCUMENT_PARENT';
export const ATTACH_DOCUMENT_UPLOADFILE = 'ATTACH_DOCUMENT_UPLOADFILE';
export const REMOVE_DOCUMENT_UPLOADFILE = 'REMOVE_DOCUMENT_UPLOADFILE';
export const ADD_DOCUMENT_CANWRITE = 'ADD_DOCUMENT_CANWRITE';
export const REMOVE_DOCUMENT_CANWRITE = 'REMOVE_DOCUMENT_CANWRITE';
export const ADD_DOCUMENT_CANREAD = 'ADD_DOCUMENT_CANREAD';
export const REMOVE_DOCUMENT_CANREAD = 'REMOVE_DOCUMENT_CANREAD';
>>>>>>> 7d06590c12612b30f22b340ceab77986fa45253d
