export const RETRIEVE_REFERENCES = 'RETRIEVE_REFERENCES';
export const EDIT_REFERENCE = 'EDIT_REFERENCES';
export const CREATE_REFERENCE = 'CREATE_REFERENCE';
export const GET_REFERENCE = 'GET_REFERENCE';
export const DELETE_REFERENCE = 'DELETE_REFERENCE';