export const REPO_REFRESH_PATH = 'REPO_REFRESH_PATH';
export const REPO_GET_FILE = 'REPO_GET_FILE';
export const REPO_PARSE_FILE = 'REPO_PARSE_FILE';
export const REPO_CLEAR_FILE = 'REPO_CLEAR_FILE';
<<<<<<< HEAD
export const REPO_UPDATE_REFS = 'REPO_UPDATE_REFS';
export const REPO_GET_LATEST_COMMIT = 'REPO_GET_LATEST_COMMIT';
=======
export const REPO_REFRESH_PATH_NEW = 'REPO_REFRESH_PATH_NEW'
export const REPO_UPDATE_REFS = 'REPO_UPDATE_REFS';
>>>>>>> f3ae564d87716300b911ba2c42e2fe4d2df7efa4
