export const GET_REPOSITORY_FILE = 'GET_REPOSITORY_FILE';
export const CREATE_REPOSITORY = 'CREATE_REPOSITORY';
export const GET_REPOSITORY = 'GET_REPOSITORY';
export const DELETE_REPOSITORY = 'DELETE_REPOSITORY';
export const RETRIEVE_REPOSITORIES = 'RETRIEVE_REPOSITORIES';
export const SET_CURRENT_REPOSITORY = 'SET_CURRENT_REPOSITORY';
