export const CREATE_REQUEST = 'CREATE_REQUEST';
export const GET_REQUEST = 'GET_REQUEST';
export const RETRIEVE_REQUESTS = 'RETRIEVE_REQUESTS';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const EDIT_REQUEST = 'EDIT_REQUEST';