export const CREATE_SNIPPET = 'CREATE_SNIPPET';
export const GET_SNIPPET = 'GET_SNIPPET';
export const RETRIEVE_SNIPPETS = 'RETRIEVE_SNIPPETS';
export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const EDIT_SNIPPET = 'EDIT_SNIPPET'
