export const SCROLL_RIGHT_VIEW = "SCROLL_RIGHT_VIEW";
export const SET_CREATION = "SET_CREATION";
export const SET_REQUEST_CREATION = "SET_REQUEST_CREATION";
export const SET_DOCUMENT_LOADED = "SET_DOCUMENT_LOADED";