export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const GET_WORKSPACE = 'GET_WORKSPACE';
export const DELETE_WORKSPACE = 'DELETE_WORKSPACE';
export const WORKSPACE_ADD_USER = 'WORKSPACE_ADD_USER';
export const WORKSPACE_REMOVE_USER = 'WORKSPACE_REMOVE_USER';
export const RETRIEVE_WORKSPACES = 'RETRIEVE_WORKSPACES';
export const SET_CURRENT_WORKSPACE = 'SET_CURRENT_WORKSPACE';
export const  SEARCH_WORKSPACE = 'SEARCH_WORKSPACE';