export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const GET_WORKSPACE = 'GET_WORKSPACE';
export const WORKSPACE_ADD_USER = 'WORKSPACE_ADD_USER';
export const WORKSPACE_REMOVE_USER = 'WORKSPACE_REMOVE_USER';