const CHECK_DOCUMENT_MAX_NUM = 10;
const CHECK_SNIPPET_MAX_NUM = 5;

const CHECK_SNIPPET_CHAR_MAX = 20;

module.exports = {
    CHECK_DOCUMENT_MAX_NUM,
    CHECK_SNIPPET_MAX_NUM,
    CHECK_SNIPPET_CHAR_MAX,
}