const JOB_SCAN_REPOSITORIES = 1;
const JOB_UPDATE_REFERENCES = 2;


const JOB_STATUS_FINISHED = 'FINISHED';
const JOB_STATUS_RUNNING = 'RUNNING';
const JOB_STATUS_ERROR = 'ERROR';


module.exports = {
    JOB_SCAN_REPOSITORIES,
    JOB_UPDATE_REFERENCES,

    JOB_STATUS_FINISHED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_ERROR
}