const SNIPPET_EXPANSION_FACTOR = 1.5;
const SNIPPET_VALID_REGION_THRESHOLD = 0.5;
const NUM_VALID_SNIPPET_START_LINES = 3;

const SNIPPET_STATUS_INVALID = 'INVALID';
const SNIPPET_STATUS_VALID = 'VALID';


module.exports = {
    SNIPPET_EXPANSION_FACTOR,
    SNIPPET_VALID_REGION_THRESHOLD,
    NUM_VALID_SNIPPET_START_LINES,
    SNIPPET_STATUS_INVALID,
    SNIPPET_STATUS_VALID
};