const JOB_PARSE_DOXYGEN = 1;
const JOB_UPDATE_SNIPPETS = 2;
const JOB_PARSE_SEMANTIC = 3;
const JOB_UPDATE_REFERENCES = 4;


const JOB_STATUS_FINISHED = 'FINISHED';
const JOB_STATUS_RUNNING = 'RUNNING';
const JOB_STATUS_ERROR = 'ERROR';


module.exports = {
    JOB_PARSE_DOXYGEN,
    JOB_UPDATE_SNIPPETS,
    JOB_PARSE_SEMANTIC,
    JOB_UPDATE_REFERENCES,

    JOB_STATUS_FINISHED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_ERROR
}