export const SET_MARKUP_MENU_ACTIVE = 'SET_MARKUP_MENU_ACTIVE';
export const SET_SNIPPET_MENU_ACTIVE = 'SET_SNIPPET_MENU_ACTIVE';
export const SET_WRITE = 'SET_WRITE';
export const SET_ATTACHMENT_MENU_ACTIVE = 'SET_ATTACHMENT_MENU_ACTIVE';